### ISSUE TITLE
Is the thesis available already ?

### ISSUE THREAD

**Issue by clemsos** [andimarafioti/AIAMI#1]
Hey, looks like a cool project. I am interested in instruments recognition as well so I will be curious to read what you have found. Is there anything published yet ?

**Comment by andimarafioti** [comment]
Hi! I am attaching you what I have published. It is written in Spanish, I am thinking about translating it but I am unsure about it being worth the effort. Thank you for being interested.
[Manuscrito Tesis.pdf](https://github.com/andimarafioti/AIAMI/files/374163/Manuscrito.Tesis.pdf)

**Comment by clemsos** [comment]
Ok thanks, I'll check it ! I don't know much Spanish but I speak French so I should manage to understand sth I guess !
